apiVersion: v2
name: application
description: Generic helm chart for all kind of applications

type: application

version: 6.14.0

keywords:
  - java
  - node
  - dotnet
  - kubernetes
  - application

home: https://github.com/KindDevOps/app_helm_chart/charts/app
maintainers:
- name: KindDevops
  email: kind.devops@gmail.com
